config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    resources :posts
  end

  resource :posts, only: :show # this should be plural so it refers to the posts resouce (posts_controller)

  root 'users#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # Here is an example of the current_user method and helper that will make you layout view work
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@user = User.find(session[:user_id])
		@posts = Post.where(user_id: session[:user_id])
	end

	def show
		@post = Post.find(params[:id]) if params[:id]
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post])
		if @post.update(params[:post])
			flash[:notice] = 'New Post created.'
		else
			flash[:alert] = 'Post not created.'
		end
	end

	def edit
		@post = Post.find(params[:id]) if params[:id]
	end

	def update
		@post = Post.find(params[:id]) if params[:id]
		if @post.update(params[:post])
			flash[:notice] = 'Post edited.'
			redirect_to user_posts_path
		else
			flash[:notice] = 'Edit incomplete.'
			redirect_to user_posts_path
		end
	end

	def destroy
		@post = Post.find(params[:id])

		if @post.destroy
			flash[:notice] = 'User successfully deleted.'
		else
			flash[:alert] = 'User delete not successful.'
		end

		redirect_to user_posts_path
		
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def destroy
		session[:user_id] = nil
		redirect_to users_path
	end

	def create
		@user = User.where(fname: params[:fname]).first
		if @user && @user.email == params[:email]
			session[:user_id] = @user.id
			flash[:notice] = 'Login Successful'
			redirect_to users_path
		else
			flash[:alert] = 'Login Failed'
			redirect_to new_session_path
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = User.find(session[:user_id]) if session[:user_id] # a 'current_user' method and helper on the application_controller could set this up app wide
		@users = User.all
		@posts = Post.all # this should really be handled through the posts_controller
	end

	def new
		@user = User.new
	end

	def profile
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			flash[:notice] = 'New user created.'
			redirect_to user_path @user
		else
			flast[:alert] = 'User not created'
			redirect_to new_user_path
		end
	end

	def show
		@user = User.find(params[:id])
		@posts = Post.where(user_id: params[:id]) # this should really be handled through the posts_controller
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(params[:user])
			flash[:notice] = 'User profile edited.'
			redirect_to user_path @user
		else
			flash[:alert] = 'Profile not updated.'
			redirect_to edit_user_path @user
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App9</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Home', users_path %>
<%= link_to 'Sign Up', new_user_path %>
	<% if session[:user_id]%>
		<%= link_to('Sign Out', session_path(session[:user_id]), method: :delete) %>
	<% else %>
		<%= link_to 'Sign In', new_session_path %>
	<% end %>
	<h1>Feats by K</h1>

	<%= yield %>


</body>
</html>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= form_for @post, url: post_path do |p| %>
	<fieldset>
		<div class="field">
			<%= p.label :body %>
			<%= p.text_field :body %>
		</div>
		<div class="actions">
			<%= p.submit %>
		</div>
	</fieldset>
<% end %>	

app/views/posts/index.html.erb
<h2><%= @user.fname %> Posts</h2>

<% @posts.each do |p| %>
	<p><%= p.body %></p>
	<% if @user.id == session[:user_id] %>
	<p><%= link_to 'Edit Post', edit_user_post_path(p.user_id, p.id)%></p>
	<p><%= link_to('Delete Post', user_post_path(p.user_id, p.id), method: :delete)%></p>
	<% end %>	
<% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= for_for @post do |p| %>
	<fieldset>
		<div class="field">
			<%= p.label :body %>
			<%= p.text_field :body %>
		</div>
		<div class="actions">
			<%= p.submit %>
		</div>
	</fieldset>
<% end %>	

app/views/posts/show.html.erb
<h2>User Post</h2>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for @user do |f| %>
	<fieldset>
		<div class="field">
			<%= f.label :fname %>
			<%= f.text_field :fname %>
		<div>
			<div class="field">
			<%= f.label :lname %>
			<%= f.text_field :lname %>
		<div>
		<div class="field">
			<%= f.label :email %>
			<%= f.text_field :email %>
		<div>
		<div class="field">
			<%= f.label :bio %>
			<%= f.text_field :bio %>
		<div>
		<div class="actions">
			<%= f.submit %>
		<div>
	</fieldset>
<% end %>	

app/views/users/index.html.erb
<% if session[:user_id] %>
	<h2>Welcome, <%= @user.fname %></h2>

	<%= link_to 'Create a post', users_post_path %>

		<% @posts.each do |p| %>
			<p><%= link_to "#{User.find(p.user_id).fname} #{User.find(p.user_id).lname}", user_path(p.user_id) %> :  <%= p.body %></p>
		<% end %>
		
		<!-- 
		A cleaner and more isolated way to handle this is as follows.
		This accesses posts throug hte user association rather than from the users controller
		so you can get rid of the @post variable on users#index
		This should also probably be in the users#show view unless you are showing a list
		of users and all their posts
		-->
		<% @user.posts.each do |post| %>
			<%= link_to post.body, post_path(post) %>
		<% end %>
<% end %>

app/views/users/new.html.erb
<h2>New User</h2>

<%= form_for @user do |f| %>
	<fieldset>
		<div class="field">
			<%= f.label :fname %>
			<%= f.text_field :fname %>
		<div>
			<div class="field">
			<%= f.label :lname %>
			<%= f.text_field :lname %>
		<div>
		<div class="field">
			<%= f.label :email %>
			<%= f.text_field :email %>
		<div>
		<div class="field">
			<%= f.label :bio %>
			<%= f.text_field :bio %>
		<div>
		<div class="actions">
			<%= f.submit %>
		<div>
	</fieldset>
<% end %>	

app/views/users/show.html.erb
<h2>User Profile</h2>

	<p><%= @user.fname %> <%= @user.lname %></p>
	<p><%= @user.email %></p>
	<br>
	<%= @user.bio %>
	<br>
	<% if @user.id == session[:user_id] %>
	<p><%= link_to 'Edit Profile', edit_user_path(session[:user_id]) %></p>
	<p><%= link_to 'Posts', user_posts_path(@user) %></p>
	<% end %>